version: '2.1'

services:
  mongodb:
    image: healthcheck/mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: SolutionDb
      TZ: Europe/Paris
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/:/data/mongodb
    networks:
      - network-solution

  microservice_solution_back:
    depends_on:
      mongodb:
        condition: service_healthy
    build:
      context: ../microservicebdd
      dockerfile: Dockerfile
    container_name: microservice-web-1.0.0
    ports:
      - 9002:9002
    environment:
      MONGODB_STATUS_HOST: mongodb
      spring.data.mongodb.uri: mongodb://root:secret@mongodb:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      spring.data.mongodb.database: SolutionDb
    networks:
      - network-solution

  angular_solution_front:
    depends_on:
      - mongodb
      - microservice_solution_back
    build:
      context: ../applicationWebAngular
      dockerfile: Dockerfile
    container_name: angular_solution_front
    volumes:
      - './angular_solution_front:/usr/src/app'
    ports:
      - '4201:4201'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4201"
    networks:
      - network-solution


networks:
  network-solution:
    driver: bridge

volumes:
  front:
