version: '3.7'

services:
  mongodb:
    user: $UID
    image: mongo:bionic
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: data
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: secret
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./data/:/data/db

